# Site settings
name: stay foolish
email: ai.xmg.go@gmail.com
# author: majinghui
# url: http://www.hifreud.com
# resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/stafolish/
# baseurl: "/LessOrMore"
description: stay hungry,stay foolish
meta_description: javaæ˜¯ä¸–ç•Œä¸Šæœ€å¥½çš„è¯­è¨€ğŸ¤£
motto: Nothing is true, everything is permitted
banner: çº¸ä¸Šå¾—æ¥ç»ˆè§‰æµ…ï¼Œç»çŸ¥æ­¤äº‹è¦èº¬è¡Œ

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: stafolish

# Build settings
markdown: kramdown

# baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

